package com.aus.deutschflow.data.local.entities

import androidx.compose.runtime.Immutable
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * One turn of a roleplay conversation, kept so the conversation survives the
 * screen.
 *
 * The chat lived only in [com.aus.deutschflow.ui.viewmodel.RoleplayViewModel]'s
 * StateFlow, which means it was gone on process death - and this is the screen a
 * user is most likely to leave mid-way, because it is the one where they stop to
 * think of a German sentence. Coming back to an empty scene with no way to resume
 * is the worst case, since the model's replies are the material.
 *
 * Only the current session is retained: starting a new scenario clears the table.
 * There is no history UI to browse past conversations, and keeping every session
 * would grow a table nothing ever reads or prunes.
 *
 * [position] is the turn's order within the session, assigned by the ViewModel
 * rather than taken from an autogenerated id, so a restored conversation and a
 * live one are ordered by the same field. It carries no @Index: a single-column
 * INTEGER PRIMARY KEY is the rowid in SQLite, so "ORDER BY position" already
 * reads in storage order and a second index would only be a duplicate to write.
 */
@Immutable
@Entity(tableName = "roleplay_messages")
data class RoleplayMessageEntity(
    @PrimaryKey val position: Int,
    val scenario: String,
    /** "user" or "assistant" — the same two values the Groq API takes. */
    val role: String,
    val content: String,
    /** The English gloss shown under an assistant turn; absent on user turns. */
    val translation: String? = null,
    val timestamp: Long = System.currentTimeMillis()
)
